### ISSUE TITLE
wrong translation

### ISSUE THREAD

**Issue by ismetsener** [DivanteLtd/pimcore-translation-bundle#7]
text in ENGLISH:
The Alfa Romeo 1900 is an automobile produced by Italian car manufacturer Alfa Romeo from 1950 to 1959. Designed by Orazio Satta, it was an important development for Alfa Romeo as the marque's first car built entirely on a production line and first production car without a separate chassis. It was also the first Alfa Romeo offered with left-hand drive. The car was introduced at the 1950 Paris Motor Show.

Source language (config.yml): "en_US"
destination language: de_DE (in pimcore   system Localization )

translation:
% 3Cp% 3Die% 20Alfa% 20Romeo% 201900% 20is% 20an% 20automobile% 20produced% 20by% 20Italian% 20car% 20manufacturer% 20Alfa% 20Romeo% 20from% 201950% 20to% 201959.% 20Designed% 20by% 20Orazio% 20Satta% 2C. 20it% 20was% 20an% 20wichtig% 20Entwicklung% 20für% 20Alfa% 20Romeo% 20as% 20the% 20marque% 27s% 20first% 20car% 20built% 20entirely% 20on% 20a% 20production% 20line% 20und% 20first% 20production% 20car% 20without% 20a% 20separate% 20chassis.% 20It% 20was% 20also% 20the% 20first% 20Alfa% 20Romeo% 20angebot% 20with% 20left-hand% 20drive.% 20The% 20car% 20was% 20 eingeführt% 20at% 20the% 201950% 20Paris% 20Motor% 20Show.% 3C% 2Fp% 3E% 0A

**Comment by prugala** [comment]
@ismetsener fixed. Please update your package to version 1.0.1

Btw. please change in your composer package from pimcore-google-translate on:
https://packagist.org/packages/divante-ltd/pimcore-translation-bundle

**Comment by ismetsener** [comment]
I changed 
It WORKS Now , thank you

**Comment by ismetsener** [comment]
how to use   "copy"  function/button?

**Comment by prugala** [comment]
This is the functionality of our one project. You can copy the value from source language field to other fields.

We will remove it from this bundle.

**Comment by ismetsener** [comment]
what is the IP-address  of the google_translate   server?
I want to allow this in my firewall

**Comment by prugala** [comment]
There you can get all IP ranges: https://www.gstatic.com/ipranges/goog.json
A better way would be to allow connection to hostname *.googleapis.com
